// Report exports for the Dashboard — Excel (data-heavy, multi-sheet) and PDF
// (clean tabular one-pager). Both run client-side from the current dashboard.

import * as XLSX from "xlsx";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { DashboardData } from "./analytics";

function stamp() {
  return new Date().toISOString().slice(0, 10); // YYYY-MM-DD
}

export interface POLine {
  sku: string;
  reorder: number;
}

export interface POOptions {
  /** The logged-in company's real name — never a fallback/sample value. */
  businessName: string;
  /** The logged-in user who clicked Generate PO. */
  generatedBy?: string;
}

/** Generate a Purchase Order PDF for the given reorder lines. */
export function exportPO(lines: POLine[], { businessName, generatedBy }: POOptions) {
  const marginX = 14;
  const pageWidth = 210;
  // Size the page to the content instead of a fixed A4, so a 1-2 line PO
  // doesn't leave most of the sheet blank (clamped to a normal A4 max, so
  // long lists still paginate the usual autoTable way).
  const pageHeight = Math.min(Math.max(114 + lines.length * 7, 130), 297);
  const doc = new jsPDF({ unit: "mm", format: [pageWidth, pageHeight] });
  const poNumber = `PO-${new Date().toISOString().slice(0, 10).replace(/-/g, "")}-${Math.floor(Math.random() * 900 + 100)}`;

  // Letterhead — the buyer's real company name, top-left.
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(0);
  doc.text(businessName, marginX, 18);

  // Status badge, top-right.
  doc.setFillColor(255, 247, 224);
  doc.roundedRect(pageWidth - marginX - 22, 12, 22, 7, 1.5, 1.5, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(180, 120, 0);
  doc.text("DRAFT", pageWidth - marginX - 11, 16.6, { align: "center" });

  // Document title + meta.
  doc.setTextColor(0);
  doc.setFontSize(20);
  doc.text("Purchase Order", marginX, 30);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(`PO #: ${poNumber}      Date: ${stamp()}`, marginX, 37);

  doc.setDrawColor(226, 232, 240);
  doc.line(marginX, 41, pageWidth - marginX, 41);

  const totalQty = lines.reduce((sum, l) => sum + l.reorder, 0);

  autoTable(doc, {
    startY: 46,
    head: [["#", "SKU / Product", "Qty to Order"]],
    body: lines.map((l, i) => [String(i + 1), l.sku, String(l.reorder)]),
    foot: [["", "Total", String(totalQty)]],
    styles: { fontSize: 10 },
    headStyles: { fillColor: [29, 78, 216] },
    footStyles: { fillColor: [241, 245, 249], textColor: 30, fontStyle: "bold" },
    margin: { left: marginX, right: marginX },
  });

  const y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(90);
  doc.text(`Generated by: ${generatedBy ?? "SmartOps user"}`, marginX, y);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(140);
  doc.text(
    "Auto-generated from SmartOps stock alerts. Confirm quantities with your supplier before dispatch.",
    marginX,
    y + 6,
    { maxWidth: pageWidth - marginX * 2 },
  );

  doc.save(`${poNumber}.pdf`);
}

function baseName(d: DashboardData) {
  const src = d.isSample ? "Sample" : d.source.replace(/\.[^.]+$/, "").replace(/[^a-z0-9]+/gi, "_");
  return `SmartOps_Report_${src}_${stamp()}`;
}

/** Multi-sheet .xlsx: one tab per report section. */
export function exportExcel(d: DashboardData) {
  const wb = XLSX.utils.book_new();

  const summary = d.kpiCards.map((c) => ({ Metric: c.label, Value: c.value, Note: c.sub ?? "" }));
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(summary), "Summary");

  XLSX.utils.book_append_sheet(
    wb,
    XLSX.utils.json_to_sheet(d.topSkus.map((s) => ({ SKU: s.sku, "Units Sold": s.units }))),
    "Top SKUs",
  );

  XLSX.utils.book_append_sheet(
    wb,
    XLSX.utils.json_to_sheet(d.abcBreakdown.map((c) => ({ Class: c.name, SKUs: c.skus, "Revenue %": c.revenuePct }))),
    "ABC",
  );

  XLSX.utils.book_append_sheet(
    wb,
    XLSX.utils.json_to_sheet(
      d.stockoutRisks.map((s) => ({
        SKU: s.sku,
        "On Hand": s.onHand,
        "Daily Sales": s.dailySales,
        "Days Left": s.daysLeft,
        "Reorder Qty": s.reorder,
      })),
    ),
    "Stockout Risks",
  );

  XLSX.utils.book_append_sheet(
    wb,
    XLSX.utils.json_to_sheet(
      d.slowMovers.map((m) => ({
        SKU: m.sku,
        Units: m.units,
        Value: m.value,
        Status: m.daysIdle > 0 ? `${m.daysIdle}d idle` : "low sales",
      })),
    ),
    "Slow Movers",
  );

  XLSX.writeFile(wb, `${baseName(d)}.xlsx`);
}

/** Clean tabular PDF report. */
export function exportPdf(d: DashboardData) {
  const doc = new jsPDF();
  const marginX = 14;

  doc.setFontSize(18);
  doc.text("SmartOps — Operations Report", marginX, 20);
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(`Source: ${d.source}   ·   Generated ${stamp()}`, marginX, 27);
  doc.setTextColor(0);

  let y = 34;
  const section = (title: string, head: string[], body: (string | number)[][]) => {
    if (body.length === 0) return;
    autoTable(doc, {
      startY: y,
      head: [[title]],
      body: [],
      theme: "plain",
      headStyles: { fontStyle: "bold", fontSize: 12, textColor: 30 },
    });
    autoTable(doc, {
      startY: (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY,
      head: [head],
      body,
      styles: { fontSize: 9 },
      headStyles: { fillColor: [29, 78, 216] },
      margin: { left: marginX, right: marginX },
    });
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  };

  section("Key Metrics", ["Metric", "Value", "Note"], d.kpiCards.map((c) => [c.label, c.value, c.sub ?? ""]));
  section(
    "Reorder Now",
    ["SKU", "On Hand", "Daily", "Days Left", "Reorder"],
    d.stockoutRisks.map((s) => [s.sku, s.onHand, s.dailySales, s.daysLeft, s.reorder]),
  );
  section(
    "Slow-Movers",
    ["SKU", "Units", "Value", "Status"],
    d.slowMovers.map((m) => [m.sku, m.units, m.value, m.daysIdle > 0 ? `${m.daysIdle}d idle` : "low sales"]),
  );
  section("Top SKUs", ["SKU", "Units Sold"], d.topSkus.map((s) => [s.sku, s.units]));
  section("ABC Classification", ["Class", "SKUs", "Revenue %"], d.abcBreakdown.map((c) => [c.name, c.skus, `${c.revenuePct}%`]));

  doc.save(`${baseName(d)}.pdf`);
}
